--- # ansible-playbook for .war deploy on host

- hosts: all
  connection: ssh
  user: shubham
  become: yes
  gather_facts: yes


  tasks:
    - name: install git 
      action: yum pkg="git" state="present"

    - name: install maven
      action: yum pkg="maven" state="present"

    - name: install docker
      action: yum pkg="docker" state="present"
      notify: start docker
      
    - name: copy
      action: copy src="/home/shubham/.jenkins/workspace/project3/gameoflife-web/target/*.war" dest="/mnt/package"


  handlers: 
    - name: start docker
      action: service name="docker" state="started"
